DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS names CASCADE;
DROP TABLE IF EXISTS choices CASCADE;
DROP TABLE IF EXISTS polls CASCADE;


CREATE TABLE polls(
  id SERIAL PRIMARY KEY,
  email_address VARCHAR(255) NOT NULL,
  question TEXT NOT NULL,
  admin_link VARCHAR(255) NOT NULL,
  poll_link VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL,
  anonymous BOOLEAN NOT NULL
);

CREATE TABLE choices(
  id SERIAL PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT
);
CREATE TABLE names(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE votes(
  id SERIAL PRIMARY KEY,
  choice_id INTEGER NOT NULL REFERENCES choices(id) ON DELETE CASCADE,
  vote_weight INTEGER NOT NULL,
  name_id INTEGER NOT NULL REFERENCES names(id) ON DELETE CASCADE
);

